### ISSUE TITLE
Problems running sockjs-ruby example server app on 1.9.3-p125 with rack 1.4.1

### ISSUE THREAD

**Issue by pkrefta** [sockjs/sockjs-ruby#3]
Hi guys,

I've problem running simple sockjs-ruby server with rack 1.4.1 - my code

``` ruby
#!/usr/bin/env ruby
# encoding: utf-8

require "thin"
require "rack"
require "rack/sockjs"
require "eventmachine"

# Your custom app.
class MyHelloWorld
  def call(env)
    body = "This is the app, not SockJS."
    headers = {
      "Content-Type" => "text/plain; charset=UTF-8",
      "Content-Length" => body.bytesize.to_s
    }

    [200, headers, [body]]
  end
end


app = Rack::Builder.new do
  # Run one SockJS app on /echo.
  use SockJS, "/echo" do |connection|
    connection.subscribe do |session, message|
      session.send(message)
    end
  end

  # ... and the other one on /close.
  use SockJS, "/close" do |connection|
    connection.session_open do |session|
      session.close(3000, "Go away!")
    end
  end

  # This app will run on other URLs than /echo and /close,
  # as these has already been assigned to SockJS.
  run MyHelloWorld.new
end


EM.run do
  thin = Rack::Handler.get("thin")
  thin.run(app.to_app, Port: 8081)
end
```

and after trying to run I'm encountering following error

```
/Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:82:in `block in use': undefined method `new' for SockJS:Module (NoMethodError)
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:130:in `[]'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:130:in `block in to_app'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:130:in `each'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:130:in `inject'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:130:in `to_app'
    from server/server.rb:46:in `block in <main>'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/null/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from server/server.rb:44:in `<main>'
```

How to fix that ?

**Comment by nanzhong** [comment]
So the documentation seems to be out of date... Also rubygems.org seems to have a different sockjs gem package than what is one git. 

Basically to fix, build the gem from git, add the `require 'thin'`, prepend SockJS with `Rack::`, and make sure that you pass an options hash with a sockjs_url defined.

Working example below.

``` ruby
#!/usr/bin/env ruby
# encoding: utf-8

require "thin"
require "rack"
require "rack/sockjs"
require "eventmachine"

# Your custom app.
class MyHelloWorld
  def call(env)
    body = "This is the app, not SockJS."
    headers = {
      "Content-Type" => "text/plain; charset=UTF-8",
      "Content-Length" => body.bytesize.to_s
    }

    [200, headers, [body]]
  end
end

options = {sockjs_url: "http://cdn.sockjs.org/sockjs-#{SockJS::PROTOCOL_VERSION}.min.js"}

app = Rack::Builder.new do
  # Run one SockJS app on /echo.
  use Rack::SockJS, "/echo", options do |connection|
    connection.subscribe do |session, message|
      session.send(message)
    end
  end

  # ... and the other one on /close.
  use Rack::SockJS, "/close", options do |connection|
    connection.session_open do |session|
      session.close(3000, "Go away!")
    end
  end

  # This app will run on other URLs than /echo and /close,
  # as these has already been assigned to SockJS.
  run MyHelloWorld.new
end

EM.run do
  thin = Rack::Handler.get("thin")
  thin.run(app.to_app, Port: 8081)
end
```

**Comment by majek** [comment]
Guys, please check out forks of other people, for example: https://github.com/nyarly/sockjs-ruby
